export const ALL_SLIDER_REQUEST = 'ALL_SLIDER_REQUEST'
export const ALL_SLIDER_SUCCESS = 'ALL_SLIDER_SUCCESS'
export const ALL_SLIDER_FAIL = 'ALL_SLIDER_FAIL'

export const ADMIN_SLIDER_REQUEST = 'ADMIN_SLIDER_REQUEST'
export const ADMIN_SLIDER_SUCCESS = 'ADMIN_SLIDER_SUCCESS'
export const ADMIN_SLIDER_FAIL = 'ADMIN_SLIDER_FAIL'

export const NEW_SLIDER_REQUEST ='NEW_SLIDER_REQUEST'
export const NEW_SLIDER_SUCCESS ='NEW_SLIDER_SUCCESS'
export const NEW_SLIDER_FAIL ='NEW_SLIDER_FAIL'
export const NEW_SLIDER_RESET = 'NEW_SLIDER_RESET'

export const DELETE_SLIDER_REQUEST = 'DELETE_SLIDER_REQUEST'
export const DELETE_SLIDER_SUCCESS = 'DELETE_SLIDER_SUCCESS'
export const DELETE_SLIDER_FAIL = 'DELETE_SLIDER_FAIL'
export const DELETE_SLIDER_RESET = 'DELETE_SLIDER_RESET'

export const UPDATE_SLIDER_REQUEST ='UPDATE_SLIDER_REQUEST'
export const UPDATE_SLIDER_SUCCESS ='UPDATE_SLIDER_SUCCESS'
export const UPDATE_SLIDER_FAIL = 'UPDATE_SLIDER_FAIL'
export const UPDATE_SLIDER_RESET = 'UPDATE_SLIDER_RESET'

export const UPDATE_SLIDER_STATUS_REQUEST ='UPDATE_SLIDER_STATUS_REQUEST'
export const UPDATE_SLIDER_STATUS_SUCCESS ='UPDATE_SLIDER_STATUS_SUCCESS'
export const UPDATE_SLIDER_STATUS_FAIL = 'UPDATE_SLIDER_STATUS_FAIL'
export const UPDATE_SLIDER_STATUS_RESET = 'UPDATE_SLIDER_STATUS_RESET'

export const SLIDER_DETAILS_REQUEST ='SLIDER_DETAILS_REQUEST'
export const SLIDER_DETAILS_SUCCESS ='SLIDER_DETAILS_SUCCESS'
export const SLIDER_DETAILS_FAIL = 'SLIDER_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'